fit_connect/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('accounts/register', views.RegisterView, name='register'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('post-job/', views.post_job, name='post_job'),
    path('profile/', views.profile, name='profile'),
    path('jobs/', views.jobs, name='jobs'),
    path('all_jobs/', views.all_jobs, name='jobs_trainer'),
    path('jobs/<int:job_id>/decline/', views.decline_job, name='decline_job'),

    #ispit
    path('topup/', views.top_up, name='top_up'),
    path('all_top_ups/', views.all_top_ups, name='all_top_ups'),
    path('admin_top_up/', views.admin_top_up, name='admin_top_up'),
    path('dispute/', views.dispute_job, name='dispute_job'), 
]

app/models.py
from django.db import models

from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    balance = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    def __str__(self):
        return f"{self.id} - {self.name}"


class TrainerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    balance = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    rating = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    number_of_jobs = models.IntegerField(default=0)
    def __str__(self):
        return f"{self.id} - {self.name}"

    

class Job(models.Model):
    class Status(models.TextChoices):
        ACCEPTED = 'accepted', "Accepted"
        PUBLISHED = 'published', "Published"

    class Title(models.TextChoices):
        TRAINING_SESSION = 'training_session', "Training session"
        CONSULTATIONS = 'consultations', "Consultations"

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    description = models.CharField(max_length=512)
    status = models.CharField(
            max_length=100, 
            choices=Status.choices,
            default=Status.PUBLISHED,
    )
    title = models.CharField(
            max_length=100,
            choices=Title.choices,
            default=Title.TRAINING_SESSION,
    )
    budget = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    start_time = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.user.name} - {self.title}"
    def delete_job(self):
        self.delete()


class Bid(models.Model):
    bidder = models.ForeignKey(TrainerProfile, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    accepted = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    declined = models.BooleanField(default=False)
    disputed = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.bidder.name} - {self.job.title} - {self.price}"


class Dispute(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    bid = models.OneToOneField(Bid, on_delete=models.CASCADE)
    reason = models.TextField(blank=False, null=False)


class TopUp(models.Model):
    code = models.CharField(max_length=12)
    expiration_date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    is_used = models.BooleanField(default=False)

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True, blank=True)
    used_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.code} - {self.expiration_date} - {self.amount} - {self.is_used}"

app/templates/app/admin_top_up.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="container">

    <div class="d-flex align-items-center text-white rounded shadow-sm bg-dark mt-5">
        <div class="text-white px-4 py-3">
            <h5 class="mb-0">Applied TopUps</h5>
            <div class="card-text"><small>List of all used Top-Ups</small></div>
        </div>
    </div>

    {% if used_topups %}
        <div class="card border-light my-3 bg-body rounded shadow-sm mt-4">
            <div class="card-body p-4">
                <table class="table table-striped table-bordered mb-0">
                    <thead>
                        <tr>
                            <th>Code</th>
                            <th>Expiration Date</th>
                            <th>Amount</th>
                            <th>Used by</th>
                            <th>Used date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for topup in used_topups %}
                        <tr>
                            <td>{{ topup.code }}</td>
                            <td>{{ topup.expiration_date }}</td>
                            <td>{{ topup.amount }}</td>
                            <td>{{ topup.user }}</td>
                            <td>{{ topup.used_date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="container-sm py-3">
                <div class="card rounded shadow-sm py-5">
                    <p class="text-center mb-0">There is no used Top-Ups right now</p>
                </div>
            </div>
        </div>
    {% endif %}


    <div class="d-flex align-items-center text-white rounded shadow-sm bg-dark mt-5">
        <div class="text-white px-4 py-3">
            <h5 class="mb-0">Available TopUps</h5>
            <div class="card-text"><small>List of all available Top-Ups</small></div>
        </div>
    </div>

    {% if unused_topups %}
        <div class="card border-light my-3 bg-body rounded shadow-sm mt-4">
            <div class="card-body p-4">
                <table class="table table-striped table-bordered mb-0">
                    <thead>
                        <tr>
                            <th>Code</th>
                            <th>Expiration Date</th>
                            <th>Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for topup in unused_topups %}
                        <tr>
                            <td>{{ topup.code }}</td>
                            <td>{{ topup.expiration_date }}</td>
                            <td>{{ topup.amount }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="container-sm py-3">
                <div class="card rounded shadow-sm py-5">
                    <p class="text-center mb-0">There is no available Top-Ups right now</p>
                </div>
            </div>
        </div>
    {% endif %}
</div>

    
    <style>
        .text-white-50 { color: rgba(255, 255, 255, .5); }
        .bg-blue { background-color: #4e73e5; }
        .bg-gray { background-color: #f8faf8; }
        body { background-color: #f8f9fa; }
        th, td{ padding: 1rem!important; }
    </style>

{% endblock %}

app/templates/app/home.html
{% extends "app/base.html" %}
{% load static %} 

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'app/css/home.css' %}">
{% endblock %}

{% block content %}

    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'app/images/heading3.png' %}" alt="Your image description" width="100%" height="100%"/>
  
            <div class="container">
                <div class="carousel-caption text-start">
                <h1>Tailored Fitness Routines</h1>
                <p>Discover personalized training sessions designed by expert trainers to meet your goals.</p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'app/images/heading2.png' %}" alt="Your image description" width="100%" height="100%"/>

            <div class="container">
                <div class="carousel-caption">
                <h1>Certified Trainer Network</h1>
                <p>Connect with certified trainers who specialize in diverse fitness areas for personalized guidance.</p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'app/images/heading1.png' %}" alt="Your image description" width="100%" height="100%"/>

            <div class="container">
                <div class="carousel-caption text-end">
                <h1>Flexible Session Scheduling</h1>
                <p>Easily book training sessions at your convenience to fit your busy lifestyle.</p>
                </div>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  
  
    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
  
    <div class="container marketing">
  
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Meet Our Expert Trainers:</h2><br>
          <p class="lead">Our team of expert trainers brings a wealth of experience and knowledge to help you reach your fitness goals. From certified personal trainers to specialized instructors in yoga, strength training, and more, each trainer is dedicated to providing personalized guidance and support tailored to your needs. Get to know our trainers and find the perfect match to elevate your fitness journey.</p>
        </div>
        <div class="col-md-5">
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto rounded-3" width="500" height="500" src="{% static 'app/images/gallery3.png' %}"/>
        </div>
      </div>
  
      <hr class="featurette-divider">
  
      <div class="row featurette">
        <div class="col-md-7 order-md-2">
          <h2 class="featurette-heading">Partnered Gyms and Facilities:</h2><br>
          <p class="lead">We're proud to partner with top-tier gyms and fitness facilities to offer you a premium training experience. From state-of-the-art equipment to spacious workout areas, our partnered gyms provide the ideal environment for you to achieve your fitness goals. Explore our network of gyms and find a location near you to start your training journey today.</p>
        </div>
        <div class="col-md-5 order-md-1">
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto rounded-3" width="500" height="500" src="{% static 'app/images/gallery2.png' %}"/>
        </div>
      </div>
  
      <hr class="featurette-divider">
  
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Community and Support:</h2><br>
          <p class="lead">At FIT-CONNECT, we believe that fitness is more than just physical exercise—it's about community and support. Join a vibrant community of like-minded individuals who share your passion for health and wellness. Whether it's through group classes, online forums, or social events, we're here to help you stay motivated and connected every step of the way. Join us and become a part of something bigger than fitness—a community dedicated to living their best lives.</p>
        </div>
        <div class="col-md-5">
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto rounded-3" width="500" height="500" src="{% static 'app/images/gallery1.png' %}"/>
        </div>
      </div>
  
      <hr class="featurette-divider">
  
      <!-- /END THE FEATURETTES -->
  
    </div><!-- /.container -->
  
  
    <!-- FOOTER -->
    <footer class="container">
      <p class="float-end"><a href="#">Back to top</a></p>
      <p>&copy; 2017–2021 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>
{% endblock %}

app/templates/app/jobs.html
{% extends "app/base.html" %} 
{% load widget_tweaks %} 
{% load static %} 

{%block extrahead %}
<link rel="stylesheet" href="{% static 'app/css/jobs.css' %}" />
{% endblock %} 

{% block content %}
<div class="container">
    <div
      class="d-flex align-items-center text-white rounded shadow-sm bg-dark mt-5"
    >
      <div class="text-white px-4 py-3">
        <h5 class="mb-0">Posted Jobs</h5>
        <div class="card-text">
          <small>View all the posted jobs and their bids</small>
        </div>
      </div>
    </div>

    {% if any_job_is_published %}
    <div class="column">
      {% for job in jobs %} 
      {% if job.status == 'published' %}
      <div class="row mt-2">
        <div class="col-lg-4 py-3 my-auto">
          <div class="rate card shadow-sm">
            <div class="rate card-header no-border">
              {% if job.title == 'consultations' %}
              <h5 class="card-title">CONSULTATIONS</h5>
              {% else %}
              <h5 class="card-title">TRAINING SESSION</h5>
              {% endif %}
            </div>
            <div class="card-body pt-0">
              <div class="widget-49">
                <div class="widget-49-title-wrapper">
                  <div class="widget-49-date-primary">
                    <span class="widget-49-date-day"
                      >{{ job.start_time|date:"d"}}</span
                    >
                    <span class="widget-49-date-month"
                      >{{ job.start_time|date:"M"|upper}}</span
                    >
                  </div>
                  <div class="widget-49-meeting-info">
                    <span class="widget-49-pro-title"
                      >Budget: {{ job.budget }}€</span
                    >
                    <span class="widget-49-meeting-time"
                      >Starting at: {{ job.start_time|time:"H:i"}}</span
                    >
                  </div>
                </div>
                <div
                  class="widget-49-meeting-points px-4"
                  style="list-style-type: none"
                >
                  <p class="widget-49-meeting-item my-2">
                    <span>Description: {{ job.description }}</span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-8 py-3">
            <div class="rate card shadow-sm h-100">
                <div class="rate card-header no-border">
                    <h5 class="card-title">BIDS</h5>
                </div>
                <div class="card-body p-4 pt-0">
                    {# Display bids on that job #} 
                    {% if job.bid_set.all.count > 0 %}
                        <div class="row">
                            {% for bid in job.bid_set.all %}
                                <div class="col-6">
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="d-flex justify-content-between p-md-1">
                                                <div class="d-flex flex-row">
                                                    <div>
                                                        <h5 class="mb-0">
                                                            {{ bid.bidder.user.first_name }} {{bid.bidder.user.last_name}}
                                                        </h5>
                                                        <p class="mb-0" style="color: #b1bac5">
                                                            &star;{{ bid.bidder.rating}}({{bid.bidder.number_of_jobs}})
                                                        </p>
                                                    </div>
                                                </div>
                                                <div class="align-self-center">
                                                    <h2 class="h2 mb-0" style="color: #4e73e5">
                                                        €{{ bid.price }}
                                                    </h2>
                                                </div>
                                            </div>
                                            <form method="post" action="{% url 'jobs' %}">
                                                {% csrf_token %}
                                                <input
                                                    type="hidden"
                                                    name="bid_id"
                                                    value="{{ bid.id }}"
                                                />
                                                <button
                                                    class="w-100 btn btn-primary mt-2"
                                                    type="submit"
                                                    name="accept_bid"
                                                >
                                                    Accept Bid
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <p class="text-center mt-4">No bids yet</p>
                    {% endif %}
                </div>
            </div>
        </div>

      </div>   
    {% endif %} 
    {% endfor %}
  </div>
  {% else %}
  <div class="row">
    <div class="container-sm py-3">
        <div class="card rounded shadow-sm py-5">
            <p class="text-center mb-0">You didn't post any jobs yet</p>
        </div>
    </div>
  </div>
  {% endif %}
</div>


<div class="container">
  <div
    class="d-flex align-items-center text-white rounded shadow-sm bg-dark mt-5"
  >
    <div class="text-white px-4 py-3">
      <h5 class="mb-0">Accepted Jobs</h5>
      <div class="card-text">
        <small>Rate trainer after job is finished</small>
      </div>
    </div>
  </div>

  {% if has_accepted_bid %}
  <div class="row">
    {% for bid in bids %} 
    {% if bid.accepted == True and bid.completed == False and bid.disputed == False %}
    <div class="col-lg-4 py-3">
      <div class="rate card shadow-sm">
        <div class="rate card-header no-border">
          {% if bid.job.title == 'consultations' %}
          <h5 class="card-title">CONSULTATIONS</h5>
          {% else %}
          <h5 class="card-title">TRAINING SESSION</h5>
          {% endif %}
        </div>
        <div class="card-body pt-0">
          <div class="widget-49">
            <div class="widget-49-title-wrapper">
              <div class="widget-49-date-primary">
                <span class="widget-49-date-day"
                  >{{ bid.job.start_time|date:"d"}}</span
                >
                <span class="widget-49-date-month"
                  >{{ bid.job.start_time|date:"M"|upper}}</span
                >
              </div>
              <div class="widget-49-meeting-info">
                <span class="widget-49-pro-title"
                  >{{ bid.bidder.user.first_name }} {{ bid.bidder.user.last_name }}</span
                >
                <span class="widget-49-meeting-time"
                  >Started at: {{ bid.job.start_time|time:"H:i"}}</span
                >
              </div>
            </div>
            <div
              class="widget-49-meeting-points px-4"
              style="list-style-type: none"
            >
              <p class="widget-49-meeting-item my-2">
                <span>Price: {{ bid.price }}€</span><br /><span
                  >Description: {{ bid.job.description }}</span
                >
              </p>
            </div>
            <div class="row">
              <div class="col">
                  <div class="widget-49-meeting-action flex-shrink-0 dropdown" style="text-align: left!important;">
                      <a href="#" class="nav-link text-decoration-none dropdown-toggle" id="rate" data-bs-toggle="dropdown" aria-expanded="false">Rate Job</a>
                      <ul class="dropdown-menu text-small shadow-sm dropdown-menu-end" aria-labelledby="rate">
                          <form method="post" action="{% url 'jobs' %}" class="px-3 pb-1">
                              {% csrf_token %}
                              <input type="hidden" name="bidder_id" value="{{ bid.id }}" />
                              <!-- Ensure the input type range has a name attribute -->
                              <input type="range" name="rating" class="form-range" min="1" max="5" step="0.5" id="customRange2" style="appearance: auto" list="values" />
                              <datalist id="values" style="display: flex; flex-direction: row; justify-content: space-between; writing-mode: horizontal-tb;">
                                  <option value="1" label="&star;"></option>
                                  <option value="2" label=" "></option>
                                  <option value="3" label=" "></option>
                                  <option value="4" label=" "></option>
                                  <option value="5" label="&#9733;"></option>
                              </datalist>
                              <li><hr class="dropdown-divider mb-1" /></li>
                              <button class="w-100 btn btn-primary mt-2" type="submit" name="rate_job">Submit Rating</button>
                          </form>
                      </ul>
                  </div>
              </div>
              <div class="col">
                  <div class="widget-49-meeting-action flex-shrink-0 dropdown">
                      <a href="#" class="nav-link text-decoration-none dropdown-toggle" id="dispute" data-bs-toggle="dropdown" aria-expanded="false">Dispute Job</a>
                      <ul class="dropdown-menu text-small shadow-sm dropdown-menu-end" aria-labelledby="dispute">
                          <form method="post" action="{% url 'dispute_job' %}" class="px-3 pb-1">
                              {% csrf_token %}
                              <input type="hidden" name="bidder_id" value="{{ bid.id }}" />
                              <textarea name="reason" class="form-control" placeholder="Enter dispute reason" required></textarea>
                              <button class="w-100 btn btn-danger mt-2" type="submit" name="dispute_job">Submit Dispute</button>
                          </form>
                      </ul>
                  </div>
              </div>
          </div>
          </div>
        </div>
      </div>
    </div>
    {% endif %} 
    {% endfor %}
  </div>
  {% else %}
  <div class="row">
    <div class="container-sm py-3">
        <div class="card rounded shadow-sm py-5">
            <p class="text-center mb-0">There is no jobs that are finished right now</p>
        </div>
    </div>
  </div>
  {% endif %}
</div>


<div class="container">
  <div class="card border-light my-3 bg-body rounded shadow-sm mt-5">
    <div class="card-header text-white bg-dark px-4 py-3">
      <h5 class="mb-0">Job History</h5>
      <div class="card-text">
        <small>View history of all finished jobs</small>
      </div>
    </div>
    <div class="card-body p-4">
      <table class="table table-striped table-bordered pb-2">
        <thead>
          <tr>
            <th>Start date and time</th>
            <th>Type</th>
            <th>Trainer name</th>
            <th>Amount</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {% for bid in bids %} 
          {% if bid.accepted == True and bid.completed == True or bid.accepted == True and bid.disputed == True %}
          <tr>
            <td>{{ bid.job.start_time }}</td>
            <td>
              {% if bid.job.title == 'consultations' %} 
              Consultations 
              {% else %}
              Training session 
              {% endif %}
            </td>
            <td>
              {{ bid.bidder.user.first_name }} {{ bid.bidder.user.last_name}}
            </td>
            <td>{{ bid.price }}€</td>
            <td>
              {% if bid.completed == True %}
                <span class="badge bg-success">Completed</span>
              {% else %}
                <span class="badge bg-danger">Disputed</span>
              {% endif %}
            </td>
          </tr>
          {% endif %} 
          {% endfor %}
        </tbody>
      </table>
      <p class="mb-0">Showing {{ accepted_completed_bids }} entries</p>
    </div>
  </div>
</div>

{% endblock content %}

app/templates/app/post_job.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}

    {% if user.is_authenticated %}
        {% if user.userprofile %}
        <div class="col text-center">
            <h1 class="mb-3 mt-5">Post a Job</h1>
        </div>

        <div class="container col-xl-10 col-xxl-8 px-4 py-4">
            <div class="col-md-10 mx-auto col-lg-5">

                <form class="px-5 pb-3 pt-5 border rounded bg-light shadow-sm" method="post">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                    <div class="form-floating mb-3">
                        <div class="alert alert-danger mb-0 text-center" role="alert">
                        {% for error in form.non_field_errors %}
                            {{ error }}
                        {% endfor %}
                        </div>
                    </div>
                    {% endif %}

                    {% for field in form.visible_fields %}
                    <div class="form-floating mb-3">
                        {% if form.is_bound %}
                            {% render_field field class="form-control is-invalid" placeholder="field.label_tag" %}
                        {% else %}
                            {% render_field field class="form-control" placeholder="field.label_tag" %}
                        {% endif %}
                        <label class="form-group col-form-label mb-0">{{ field.label_tag }}</label>
                    </div>
                    {% endfor %}

                    <button class="w-100 btn btn-lg btn-primary" type="submit">Post</button>
                    <hr class="my-4">
                    <small class="text-muted text-center"><p>By clicking Post, you agree to the terms of use.</p></small>
                </form>
            </div>
        </div>
        {% else %}
            <p>Your account doesn't have access to this page. Only Users can post a job.</p>
        {% endif %}
    {% endif %}

{% endblock %}

app/templates/app/profile.html
{% extends "app/base.html" %}
{% load static %} 

{% block content %}

  <div class="container">
    <div class="container">
      {% if user.is_authenticated %}
      <div class="d-flex align-items-center text-white rounded shadow-sm bg-dark mt-5">
        <div class="text-white px-4 py-3">
            <h1 class="mb-0">Profile site</h1>
        </div>
      </div>
      <br>

      <div class="row">
        <div class="col-md-8">
          <div class="card px-5 pb-5 pt-5 shadow-sm h-100">
            <div class="user-info">
                {% if user.trainerprofile %}
                  <h2>Trainer Info</h2>
                {% endif %}
                {% if user.userprofile %}
                  <h2>User Info</h2>
                {% endif %}
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>First Name:</strong> {{ user.first_name }}</li>
                <li class="list-group-item"><strong>Last Name:</strong> {{ user.last_name }}</li>
                <li class="list-group-item"><strong>Username:</strong> {{ user.username }}</li>
                <li class="list-group-item"><strong>Email:</strong> {{ user.email }}</li>
                {% if user.trainerprofile %}
                <li class="list-group-item"><strong>Balance:</strong> {{ user.trainerprofile.balance }}€</li>
                <br>
                <li class="list-group-item"><strong>Number of finished jobs:</strong> {{ user.trainerprofile.number_of_jobs }}</li>
                <li class="list-group-item"><strong>Rating:</strong> {{ user.trainerprofile.rating }}</li>
                {% endif %}
                {% if user.userprofile %}
                <li class="list-group-item"><strong>Balance:</strong> {{ user.userprofile.balance }}€</li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card shadow-sm h-100">
              <img src="{% static 'app/images/profile.PNG' %}" class="card-img-top" alt="...">
              <div class="card-body d-flex flex-column justify-content-center align-items-center">
                  <h4 class="mb-0">{{ user.first_name }} {{ user.last_name }}</h4>
              </div>
          </div>
        </div>
      </div> 
    {% endif %}   
  </div>

  <style>
    body { background-color: #f8f9fa; }
  </style>

{% endblock content %}